version: "3.8"

services:
  prestashop:
    image: ku1son/be_198068_prestashop:latest
    environment:
      DB_SERVER: "admin-mysql_db"
      DB_NAME: "BE_198068"
      DB_USER: "root"
      DB_PASSWD: "student"

      PS_INSTALL_AUTO: "0"
      PS_LANGUAGE: "pl"
      PS_COUNTRY: "PL"
      PS_DEV_MODE: "0"

    ports:
      - "19806:80"
      - "19807:433"

    networks:
      - admin-mysql_default

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M

networks:
  admin-mysql_default:
    external: true