services:
  prestashop:
    image: prestashop/prestashop:latest
    ports:
      - "8080:80"
    environment:
      PS_DEV_MODE: 1
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASS: prestashop_password
    volumes:
      - prestashop:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop_password
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  prestashop_data:
  db_data: