services:
  prestashop:
    platform: linux/amd64
    image: prestashop/prestashop:1.7.8
    ports:
      - "8080:80"
    environment:
      PS_DEV_MODE: 1
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASS: prestashop_password
      PS_INSTALL_AUTO: 0
    volumes:
      #- prestashop:/var/www/html
      - ./prestashop:/var/www/html
    depends_on:
      - db

  db:
    platform: linux/amd64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop_password
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"   # panel WWW
      - "1025:1025"   # SMTP  

volumes:
  db_data: